/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_DataObject */

#ifndef _Included_org_haggle_DataObject
#define _Included_org_haggle_DataObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_haggle_DataObject
 * Method:    newEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_DataObject_newEmpty
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    newFromFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_DataObject_newFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_haggle_DataObject
 * Method:    newFromBuffer
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_DataObject_newFromBuffer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_haggle_DataObject
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_haggle_DataObject_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    addAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_DataObject_addAttribute
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     org_haggle_DataObject
 * Method:    getAttribute
 * Signature: (Ljava/lang/String;I)Lorg/haggle/Attribute;
 */
JNIEXPORT jobject JNICALL Java_org_haggle_DataObject_getAttribute__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_haggle_DataObject
 * Method:    getAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/haggle/Attribute;
 */
JNIEXPORT jobject JNICALL Java_org_haggle_DataObject_getAttribute__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_haggle_DataObject
 * Method:    getNumAttributes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_haggle_DataObject_getNumAttributes
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    getAttributes
 * Signature: ()[Lorg/haggle/Attribute;
 */
JNIEXPORT jobjectArray JNICALL Java_org_haggle_DataObject_getAttributes
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    getFilePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_haggle_DataObject_getFilePath
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    getFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_haggle_DataObject_getFileName
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    addFileHash
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_DataObject_addFileHash
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    setCreateTime
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_DataObject_setCreateTime__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_haggle_DataObject
 * Method:    setCreateTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_DataObject_setCreateTime__
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    setThumbnail
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_DataObject_setThumbnail
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_haggle_DataObject
 * Method:    getThumbnailSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_haggle_DataObject_getThumbnailSize
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_DataObject
 * Method:    getThumbnail
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_haggle_DataObject_getThumbnail
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_haggle_DataObject
 * Method:    getRaw
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_haggle_DataObject_getRaw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
