/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_EventHandler */

#ifndef _Included_org_haggle_EventHandler
#define _Included_org_haggle_EventHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef org_haggle_EventHandler_EVENT_HAGGLE_SHUTDOWN
#define org_haggle_EventHandler_EVENT_HAGGLE_SHUTDOWN 0L
#undef org_haggle_EventHandler_EVENT_NEIGHBOR_UPDATE
#define org_haggle_EventHandler_EVENT_NEIGHBOR_UPDATE 1L
#undef org_haggle_EventHandler_EVENT_NEW_DATAOBJECT
#define org_haggle_EventHandler_EVENT_NEW_DATAOBJECT 2L
#undef org_haggle_EventHandler_EVENT_INTEREST_LIST_UPDATE
#define org_haggle_EventHandler_EVENT_INTEREST_LIST_UPDATE 3L
#ifdef __cplusplus
}
#endif
#endif
