/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_Interface */

#ifndef _Included_org_haggle_Interface
#define _Included_org_haggle_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_haggle_Interface
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_haggle_Interface_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Interface
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Interface_getType
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Interface
 * Method:    getStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Interface_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Interface
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_haggle_Interface_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Interface
 * Method:    getIdentifierString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_haggle_Interface_getIdentifierString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
