/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_LaunchCallback */

#ifndef _Included_org_haggle_LaunchCallback
#define _Included_org_haggle_LaunchCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
