/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_Handle_AlreadyRegisteredException */

#ifndef _Included_org_haggle_Handle_AlreadyRegisteredException
#define _Included_org_haggle_Handle_AlreadyRegisteredException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_haggle_Handle_AlreadyRegisteredException_serialVersionUID
#define org_haggle_Handle_AlreadyRegisteredException_serialVersionUID -3042686055658047285LL
#undef org_haggle_Handle_AlreadyRegisteredException_serialVersionUID
#define org_haggle_Handle_AlreadyRegisteredException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
