/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_Attribute */

#ifndef _Included_org_haggle_Attribute
#define _Included_org_haggle_Attribute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_haggle_Attribute
 * Method:    nativeNew
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Attribute_nativeNew
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     org_haggle_Attribute
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_haggle_Attribute_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Attribute
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_haggle_Attribute_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Attribute
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_haggle_Attribute_getValue
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Attribute
 * Method:    getWeight
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_haggle_Attribute_getWeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
