/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_Node_NodeException */

#ifndef _Included_org_haggle_Node_NodeException
#define _Included_org_haggle_Node_NodeException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_haggle_Node_NodeException_serialVersionUID
#define org_haggle_Node_NodeException_serialVersionUID -3042686055658047285LL
#undef org_haggle_Node_NodeException_serialVersionUID
#define org_haggle_Node_NodeException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
