/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_haggle_Handle */

#ifndef _Included_org_haggle_Handle
#define _Included_org_haggle_Handle
#ifdef __cplusplus
extern "C" {
#endif
#undef org_haggle_Handle_HAGGLE_ERROR
#define org_haggle_Handle_HAGGLE_ERROR -100L
#undef org_haggle_Handle_HAGGLE_BUSY_ERROR
#define org_haggle_Handle_HAGGLE_BUSY_ERROR -96L
#undef org_haggle_Handle_HAGGLE_NO_ERROR
#define org_haggle_Handle_HAGGLE_NO_ERROR 0L
#undef org_haggle_Handle_HAGGLE_DAEMON_ERROR
#define org_haggle_Handle_HAGGLE_DAEMON_ERROR -100L
#undef org_haggle_Handle_HAGGLE_DAEMON_NOT_RUNNING
#define org_haggle_Handle_HAGGLE_DAEMON_NOT_RUNNING 0L
#undef org_haggle_Handle_HAGGLE_DAEMON_RUNNING
#define org_haggle_Handle_HAGGLE_DAEMON_RUNNING 1L
#undef org_haggle_Handle_HAGGLE_DAEMON_CRASHED
#define org_haggle_Handle_HAGGLE_DAEMON_CRASHED 2L
/*
 * Class:     org_haggle_Handle
 * Method:    getHandle
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_getHandle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_haggle_Handle
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_haggle_Handle_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    setDataPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_haggle_Handle_setDataPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_haggle_Handle
 * Method:    unregister
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_haggle_Handle_unregister
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_haggle_Handle
 * Method:    getSessionId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_getSessionId
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    registerEventInterest
 * Signature: (ILorg/haggle/EventHandler;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_registerEventInterest
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    publishDataObject
 * Signature: (Lorg/haggle/DataObject;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_publishDataObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    registerInterest
 * Signature: (Lorg/haggle/Attribute;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_registerInterest
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    registerInterests
 * Signature: ([Lorg/haggle/Attribute;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_registerInterests
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_haggle_Handle
 * Method:    unregisterInterest
 * Signature: (Lorg/haggle/Attribute;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_unregisterInterest
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    unregisterInterests
 * Signature: ([Lorg/haggle/Attribute;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_unregisterInterests
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_haggle_Handle
 * Method:    getApplicationInterestsAsync
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_getApplicationInterestsAsync
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    getDataObjectsAsync
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_getDataObjectsAsync
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    deleteDataObjectById
 * Signature: ([CZ)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_deleteDataObjectById___3CZ
  (JNIEnv *, jobject, jcharArray, jboolean);

/*
 * Class:     org_haggle_Handle
 * Method:    deleteDataObject
 * Signature: (Lorg/haggle/DataObject;Z)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_deleteDataObject__Lorg_haggle_DataObject_2Z
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_haggle_Handle
 * Method:    deleteDataObjectById
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_deleteDataObjectById___3C
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     org_haggle_Handle
 * Method:    deleteDataObject
 * Signature: (Lorg/haggle/DataObject;)I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_deleteDataObject__Lorg_haggle_DataObject_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    sendNodeDescription
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_sendNodeDescription
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    eventLoopRunAsync
 * Signature: (Lorg/haggle/EventHandler;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_eventLoopRunAsync__Lorg_haggle_EventHandler_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    eventLoopRunAsync
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_eventLoopRunAsync__
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    eventLoopRun
 * Signature: (Lorg/haggle/EventHandler;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_eventLoopRun__Lorg_haggle_EventHandler_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    eventLoopRun
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_eventLoopRun__
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    eventLoopStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_eventLoopStop
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    eventLoopIsRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_eventLoopIsRunning
  (JNIEnv *, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    getDaemonPid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_haggle_Handle_getDaemonPid
  (JNIEnv *, jclass);

/*
 * Class:     org_haggle_Handle
 * Method:    getDaemonStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_haggle_Handle_getDaemonStatus
  (JNIEnv *, jclass);

/*
 * Class:     org_haggle_Handle
 * Method:    spawnDaemon
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_spawnDaemon__
  (JNIEnv *, jclass);

/*
 * Class:     org_haggle_Handle
 * Method:    spawnDaemon
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_spawnDaemon__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_haggle_Handle
 * Method:    spawnDaemon
 * Signature: (Lorg/haggle/LaunchCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_spawnDaemon__Lorg_haggle_LaunchCallback_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_haggle_Handle
 * Method:    spawnDaemon
 * Signature: (Ljava/lang/String;Lorg/haggle/LaunchCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_haggle_Handle_spawnDaemon__Ljava_lang_String_2Lorg_haggle_LaunchCallback_2
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
