#!/usr/bin/python

# Copyright (c) 2014 SRI International
# Developed under DARPA contract N66001-11-C-4022.
# Authors:
#   Hasnain Lakhani (HL)

import sys
sys.path.append("/usr/sbin")
import config
import cored
from core.service import CoreService

base = config.TestFrameworkConfig()

class HaggleService(CoreService):
    ''' This is a sample user-defined service. 
    '''
    # a unique name is required, without spaces
    _name = "HaggleService"
    # you can create your own group here
    _group = "Utility"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ('/home/%s/.Haggle/' % base.whoami,)
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('haggleservice.sh', )
    # this controls the starting order vs other enabled services
    _startindex = 50
    # list of startup commands, also may be generated during startup
    _startup = ('sh haggleservice.sh', )
    # list of shutdown commands
    _shutdown = ('/bin/su -l %s -c \"%s -x nop\"' % (base.whoami, base.coreHaggleTest), )

    @classmethod
    def updateFrameworkConfig(cls, cfg):
        cls.cfg = cfg
        cls._dirs = ('/home/%s/.Haggle/' % cls.cfg.whoami,)
        cls._shutdown = ('/bin/su -l %s -c \"%s -x nop\"' % (cls.cfg.whoami, cls.cfg.coreHaggleTest), )

    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
        cfg = "#!/bin/sh\n"
        cfg += "# this file, haggleservice.sh, auto-generated by HaggleService (linux_haggle_services.py)\n"
        cfg += "/sbin/ifconfig eth0 broadcast 10.0.0.255\n"
        cfg += "/sbin/route add default eth0\n"
        cfg += "cp %s home.%s..Haggle./config.xml\n" % (cls.cfg.tmpConfigLocation, cls.cfg.whoami)
        cfg += "chown -R %s:%s /home/%s/.Haggle\n" % (cls.cfg.whoami, cls.cfg.whoami, cls.cfg.whoami)
        cfg += "/bin/su -l %s -c \"%s %s\"\n" % (cls.cfg.whoami, cls.cfg.coreHaggle, cls.cfg.coreHaggleOptions)
        return cfg
