# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_haggle', [dirname(__file__)])
        except ImportError:
            import _haggle
            return _haggle
        if fp is not None:
            try:
                _mod = imp.load_module('_haggle', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _haggle = swig_import_helper()
    del swig_import_helper
else:
    import _haggle
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


LIBHAGGLE_EVENT_SHUTDOWN = _haggle.LIBHAGGLE_EVENT_SHUTDOWN
LIBHAGGLE_EVENT_NEIGHBOR_UPDATE = _haggle.LIBHAGGLE_EVENT_NEIGHBOR_UPDATE
LIBHAGGLE_EVENT_NEW_DATAOBJECT = _haggle.LIBHAGGLE_EVENT_NEW_DATAOBJECT
LIBHAGGLE_EVENT_INTEREST_LIST = _haggle.LIBHAGGLE_EVENT_INTEREST_LIST
_LIBHAGGLE_NUM_EVENTS = _haggle._LIBHAGGLE_NUM_EVENTS

def getHaggleHandle(*args):
  return _haggle.getHaggleHandle(*args)
getHaggleHandle = _haggle.getHaggleHandle

def haggle_handle_get(*args):
  return _haggle.haggle_handle_get(*args)
haggle_handle_get = _haggle.haggle_handle_get

def haggle_handle_free(*args):
  return _haggle.haggle_handle_free(*args)
haggle_handle_free = _haggle.haggle_handle_free

def haggle_daemon_pid(*args):
  return _haggle.haggle_daemon_pid(*args)
haggle_daemon_pid = _haggle.haggle_daemon_pid

def haggle_daemon_spawn(*args):
  return _haggle.haggle_daemon_spawn(*args)
haggle_daemon_spawn = _haggle.haggle_daemon_spawn

def haggle_daemon_spawn_with_callback(*args):
  return _haggle.haggle_daemon_spawn_with_callback(*args)
haggle_daemon_spawn_with_callback = _haggle.haggle_daemon_spawn_with_callback

def haggle_unregister(*args):
  return _haggle.haggle_unregister(*args)
haggle_unregister = _haggle.haggle_unregister

def haggle_handle_get_session_id(*args):
  return _haggle.haggle_handle_get_session_id(*args)
haggle_handle_get_session_id = _haggle.haggle_handle_get_session_id

def haggle_ipc_publish_dataobject(*args):
  return _haggle.haggle_ipc_publish_dataobject(*args)
haggle_ipc_publish_dataobject = _haggle.haggle_ipc_publish_dataobject

def haggle_ipc_register_event_interest(*args):
  return _haggle.haggle_ipc_register_event_interest(*args)
haggle_ipc_register_event_interest = _haggle.haggle_ipc_register_event_interest

def haggle_ipc_register_event_interest_with_arg(*args):
  return _haggle.haggle_ipc_register_event_interest_with_arg(*args)
haggle_ipc_register_event_interest_with_arg = _haggle.haggle_ipc_register_event_interest_with_arg

def haggle_ipc_add_application_interest(*args):
  return _haggle.haggle_ipc_add_application_interest(*args)
haggle_ipc_add_application_interest = _haggle.haggle_ipc_add_application_interest

def haggle_ipc_add_application_interest_weighted(*args):
  return _haggle.haggle_ipc_add_application_interest_weighted(*args)
haggle_ipc_add_application_interest_weighted = _haggle.haggle_ipc_add_application_interest_weighted

def haggle_ipc_add_application_interests(*args):
  return _haggle.haggle_ipc_add_application_interests(*args)
haggle_ipc_add_application_interests = _haggle.haggle_ipc_add_application_interests

def haggle_ipc_remove_application_interest(*args):
  return _haggle.haggle_ipc_remove_application_interest(*args)
haggle_ipc_remove_application_interest = _haggle.haggle_ipc_remove_application_interest

def haggle_ipc_remove_application_interests(*args):
  return _haggle.haggle_ipc_remove_application_interests(*args)
haggle_ipc_remove_application_interests = _haggle.haggle_ipc_remove_application_interests

def haggle_ipc_get_application_interests_async(*args):
  return _haggle.haggle_ipc_get_application_interests_async(*args)
haggle_ipc_get_application_interests_async = _haggle.haggle_ipc_get_application_interests_async

def haggle_ipc_get_data_objects_async(*args):
  return _haggle.haggle_ipc_get_data_objects_async(*args)
haggle_ipc_get_data_objects_async = _haggle.haggle_ipc_get_data_objects_async

def haggle_ipc_delete_data_object_by_id_bloomfilter(*args):
  return _haggle.haggle_ipc_delete_data_object_by_id_bloomfilter(*args)
haggle_ipc_delete_data_object_by_id_bloomfilter = _haggle.haggle_ipc_delete_data_object_by_id_bloomfilter

def haggle_ipc_delete_data_object_bloomfilter(*args):
  return _haggle.haggle_ipc_delete_data_object_bloomfilter(*args)
haggle_ipc_delete_data_object_bloomfilter = _haggle.haggle_ipc_delete_data_object_bloomfilter

def haggle_ipc_delete_data_object_by_id(*args):
  return _haggle.haggle_ipc_delete_data_object_by_id(*args)
haggle_ipc_delete_data_object_by_id = _haggle.haggle_ipc_delete_data_object_by_id

def haggle_ipc_delete_data_object(*args):
  return _haggle.haggle_ipc_delete_data_object(*args)
haggle_ipc_delete_data_object = _haggle.haggle_ipc_delete_data_object

def haggle_ipc_send_node_description(*args):
  return _haggle.haggle_ipc_send_node_description(*args)
haggle_ipc_send_node_description = _haggle.haggle_ipc_send_node_description

def haggle_ipc_shutdown(*args):
  return _haggle.haggle_ipc_shutdown(*args)
haggle_ipc_shutdown = _haggle.haggle_ipc_shutdown

def haggle_event_loop_is_running(*args):
  return _haggle.haggle_event_loop_is_running(*args)
haggle_event_loop_is_running = _haggle.haggle_event_loop_is_running

def haggle_event_loop_run(*args):
  return _haggle.haggle_event_loop_run(*args)
haggle_event_loop_run = _haggle.haggle_event_loop_run

def haggle_event_loop_run_async(*args):
  return _haggle.haggle_event_loop_run_async(*args)
haggle_event_loop_run_async = _haggle.haggle_event_loop_run_async

def haggle_event_loop_stop(*args):
  return _haggle.haggle_event_loop_stop(*args)
haggle_event_loop_stop = _haggle.haggle_event_loop_stop

def haggle_event_loop_register_callbacks(*args):
  return _haggle.haggle_event_loop_register_callbacks(*args)
haggle_event_loop_register_callbacks = _haggle.haggle_event_loop_register_callbacks

def haggle_dataobject_new():
  return _haggle.haggle_dataobject_new()
haggle_dataobject_new = _haggle.haggle_dataobject_new

def haggle_dataobject_new_from_file(*args):
  return _haggle.haggle_dataobject_new_from_file(*args)
haggle_dataobject_new_from_file = _haggle.haggle_dataobject_new_from_file

def haggle_dataobject_new_from_buffer(*args):
  return _haggle.haggle_dataobject_new_from_buffer(*args)
haggle_dataobject_new_from_buffer = _haggle.haggle_dataobject_new_from_buffer

def haggle_dataobject_new_from_raw(*args):
  return _haggle.haggle_dataobject_new_from_raw(*args)
haggle_dataobject_new_from_raw = _haggle.haggle_dataobject_new_from_raw

def haggle_dataobject_free(*args):
  return _haggle.haggle_dataobject_free(*args)
haggle_dataobject_free = _haggle.haggle_dataobject_free

def haggle_dataobject_calculate_id(*args):
  return _haggle.haggle_dataobject_calculate_id(*args)
haggle_dataobject_calculate_id = _haggle.haggle_dataobject_calculate_id

def haggle_dataobject_set_flags(*args):
  return _haggle.haggle_dataobject_set_flags(*args)
haggle_dataobject_set_flags = _haggle.haggle_dataobject_set_flags

def haggle_dataobject_unset_flags(*args):
  return _haggle.haggle_dataobject_unset_flags(*args)
haggle_dataobject_unset_flags = _haggle.haggle_dataobject_unset_flags

def haggle_dataobject_set_createtime(*args):
  return _haggle.haggle_dataobject_set_createtime(*args)
haggle_dataobject_set_createtime = _haggle.haggle_dataobject_set_createtime

def haggle_dataobject_get_data_size(*args):
  return _haggle.haggle_dataobject_get_data_size(*args)
haggle_dataobject_get_data_size = _haggle.haggle_dataobject_get_data_size

def haggle_dataobject_read_data_start(*args):
  return _haggle.haggle_dataobject_read_data_start(*args)
haggle_dataobject_read_data_start = _haggle.haggle_dataobject_read_data_start

def haggle_dataobject_read_data_stop(*args):
  return _haggle.haggle_dataobject_read_data_stop(*args)
haggle_dataobject_read_data_stop = _haggle.haggle_dataobject_read_data_stop

def haggle_dataobject_read_data(*args):
  return _haggle.haggle_dataobject_read_data(*args)
haggle_dataobject_read_data = _haggle.haggle_dataobject_read_data

def haggle_dataobject_get_data_all(*args):
  return _haggle.haggle_dataobject_get_data_all(*args)
haggle_dataobject_get_data_all = _haggle.haggle_dataobject_get_data_all

def haggle_dataobject_get_raw(*args):
  return _haggle.haggle_dataobject_get_raw(*args)
haggle_dataobject_get_raw = _haggle.haggle_dataobject_get_raw

def haggle_dataobject_get_raw_length(*args):
  return _haggle.haggle_dataobject_get_raw_length(*args)
haggle_dataobject_get_raw_length = _haggle.haggle_dataobject_get_raw_length

def haggle_dataobject_get_raw_alloc(*args):
  return _haggle.haggle_dataobject_get_raw_alloc(*args)
haggle_dataobject_get_raw_alloc = _haggle.haggle_dataobject_get_raw_alloc

def haggle_dataobject_to_metadata(*args):
  return _haggle.haggle_dataobject_to_metadata(*args)
haggle_dataobject_to_metadata = _haggle.haggle_dataobject_to_metadata

def haggle_dataobject_get_filename(*args):
  return _haggle.haggle_dataobject_get_filename(*args)
haggle_dataobject_get_filename = _haggle.haggle_dataobject_get_filename

def haggle_dataobject_set_filename(*args):
  return _haggle.haggle_dataobject_set_filename(*args)
haggle_dataobject_set_filename = _haggle.haggle_dataobject_set_filename

def haggle_dataobject_get_filepath(*args):
  return _haggle.haggle_dataobject_get_filepath(*args)
haggle_dataobject_get_filepath = _haggle.haggle_dataobject_get_filepath

def haggle_dataobject_set_filepath(*args):
  return _haggle.haggle_dataobject_set_filepath(*args)
haggle_dataobject_set_filepath = _haggle.haggle_dataobject_set_filepath

def haggle_dataobject_add_hash(*args):
  return _haggle.haggle_dataobject_add_hash(*args)
haggle_dataobject_add_hash = _haggle.haggle_dataobject_add_hash

def haggle_dataobject_set_thumbnail(*args):
  return _haggle.haggle_dataobject_set_thumbnail(*args)
haggle_dataobject_set_thumbnail = _haggle.haggle_dataobject_set_thumbnail

def haggle_dataobject_read_thumbnail(*args):
  return _haggle.haggle_dataobject_read_thumbnail(*args)
haggle_dataobject_read_thumbnail = _haggle.haggle_dataobject_read_thumbnail

def haggle_dataobject_get_thumbnail_size(*args):
  return _haggle.haggle_dataobject_get_thumbnail_size(*args)
haggle_dataobject_get_thumbnail_size = _haggle.haggle_dataobject_get_thumbnail_size

def haggle_dataobject_add_attribute(*args):
  return _haggle.haggle_dataobject_add_attribute(*args)
haggle_dataobject_add_attribute = _haggle.haggle_dataobject_add_attribute

def haggle_dataobject_add_attribute_weighted(*args):
  return _haggle.haggle_dataobject_add_attribute_weighted(*args)
haggle_dataobject_add_attribute_weighted = _haggle.haggle_dataobject_add_attribute_weighted

def haggle_dataobject_get_num_attributes(*args):
  return _haggle.haggle_dataobject_get_num_attributes(*args)
haggle_dataobject_get_num_attributes = _haggle.haggle_dataobject_get_num_attributes

def haggle_dataobject_get_attribute_n(*args):
  return _haggle.haggle_dataobject_get_attribute_n(*args)
haggle_dataobject_get_attribute_n = _haggle.haggle_dataobject_get_attribute_n

def haggle_dataobject_get_attribute_by_name(*args):
  return _haggle.haggle_dataobject_get_attribute_by_name(*args)
haggle_dataobject_get_attribute_by_name = _haggle.haggle_dataobject_get_attribute_by_name

def haggle_dataobject_get_attribute_by_name_n(*args):
  return _haggle.haggle_dataobject_get_attribute_by_name_n(*args)
haggle_dataobject_get_attribute_by_name_n = _haggle.haggle_dataobject_get_attribute_by_name_n

def haggle_dataobject_get_attribute_by_name_value(*args):
  return _haggle.haggle_dataobject_get_attribute_by_name_value(*args)
haggle_dataobject_get_attribute_by_name_value = _haggle.haggle_dataobject_get_attribute_by_name_value

def haggle_dataobject_get_attributelist(*args):
  return _haggle.haggle_dataobject_get_attributelist(*args)
haggle_dataobject_get_attributelist = _haggle.haggle_dataobject_get_attributelist

def haggle_dataobject_remove_attribute(*args):
  return _haggle.haggle_dataobject_remove_attribute(*args)
haggle_dataobject_remove_attribute = _haggle.haggle_dataobject_remove_attribute

def haggle_dataobject_remove_attribute_by_name_value(*args):
  return _haggle.haggle_dataobject_remove_attribute_by_name_value(*args)
haggle_dataobject_remove_attribute_by_name_value = _haggle.haggle_dataobject_remove_attribute_by_name_value

def haggle_dataobject_get_metadata(*args):
  return _haggle.haggle_dataobject_get_metadata(*args)
haggle_dataobject_get_metadata = _haggle.haggle_dataobject_get_metadata

def haggle_dataobject_add_metadata(*args):
  return _haggle.haggle_dataobject_add_metadata(*args)
haggle_dataobject_add_metadata = _haggle.haggle_dataobject_add_metadata

cvar = _haggle.cvar

